package com.d24.hms.util;

public enum Routes {
    WELCOME_FORM,
    LOGIN_FORM,
    DASHBOARD_FORM,
    STUDENT_FORM,
    RESERVATION_FORM,
    ROOM_FORM,
    USER_FORM,
    POPUP_STUDENT_SAVE_FORM,
    POPUP_STUDENT_EDIT_FORM,
    POPUP_ROOM_EDIT_FORM,
    POPUP_ROOM_SAVE_FORM,
    POPUP_RESERVATION_SAVE_FORM,
    POPUP_RESERVATION_EDIT_FORM
}
